import type { Metadata } from "next";
import { Poppins, Geist_Mono } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                // Ignore browser extension errors in dev overlay
                window.addEventListener('error', function(e) {
                  if (e.filename && (e.filename.indexOf('chrome-extension') !== -1 || e.filename.indexOf('extension') !== -1)) {
                    e.stopImmediatePropagation();
                  }
                });
                window.addEventListener('unhandledrejection', function(e) {
                  if (e.reason && e.reason.stack && (e.reason.stack.indexOf('chrome-extension') !== -1 || e.reason.stack.indexOf('extension') !== -1)) {
                    e.stopImmediatePropagation();
                  }
                });

                var theme = localStorage.getItem("theme") || "system";
                var root = document.documentElement;
                if (theme === "system") {
                  var systemTheme = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
                  root.setAttribute("data-theme", systemTheme);
                } else {
                  root.setAttribute("data-theme", theme);
                }
              })();
            `,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}

